name: CI

on:
  push:
    branches:
      - '**' # Run on all branches, ignore tags.
  pull_request:

env:
  GRADLE_OPTS: "-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"

concurrency:
  cancel-in-progress: true
  group: build-${{ github.event.pull_request.number || github.event.after }}

jobs:
  test-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            tasks: check
          - os: windows-latest
            tasks: mingwX64Test
          - os: macos-latest
            tasks: macosX64Test macosArm64Test iosX64Test iosSimulatorArm64Test tvosX64Test tvosSimulatorArm64Test watchosX64Test watchosSimulatorArm64Test
    runs-on: ${{ matrix.os }}
    name: Test on ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v6.0.0
        with:
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5.0.0

      - name: Set up JDK
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0

      - name: Cache konan dependencies
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
              ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew ${{ matrix.tasks }}
